import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  client: {
    NEXT_PUBLIC_SERVER_URL: z.url(),
    NEXT_PUBLIC_SUPABASE_URL: z.url(),
    NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string().min(1),
    NEXT_PUBLIC_ELEVENLABS_GUIDE_AGENT_ID: z.string().min(1).optional(),
    NEXT_PUBLIC_ELEVENLABS_GUIDE_DEMO_MODE: z.enum(["true", "false"]).optional(),
    NEXT_PUBLIC_ELEVENLABS_GUIDE_ENABLE_AGENT_OVERRIDES: z.enum(["true", "false"]).optional(),
    NEXT_PUBLIC_ELEVENLABS_GUIDE_ENABLE_TTS_OVERRIDES: z.enum(["true", "false"]).optional(),
    NEXT_PUBLIC_ELEVENLABS_GUIDE_SECTION_DWELL_MS: z.coerce.number().int().positive().optional(),
    NEXT_PUBLIC_ELEVENLABS_GUIDE_SECTION_GAP_MS: z.coerce.number().int().min(0).optional(),
    NEXT_PUBLIC_ELEVENLABS_GUIDE_HIGHLIGHT_DWELL_MS: z.coerce.number().int().positive().optional(),
    NEXT_PUBLIC_ELEVENLABS_GUIDE_SCROLL_MS: z.coerce.number().int().positive().optional(),
    NEXT_PUBLIC_ELEVENLABS_GUIDE_TTS_SPEED: z.coerce.number().min(0.7).max(1.2).optional(),
  },
  runtimeEnv: {
    NEXT_PUBLIC_SERVER_URL: process.env.NEXT_PUBLIC_SERVER_URL,
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    NEXT_PUBLIC_ELEVENLABS_GUIDE_AGENT_ID:
      process.env.NEXT_PUBLIC_ELEVENLABS_GUIDE_AGENT_ID,
    NEXT_PUBLIC_ELEVENLABS_GUIDE_DEMO_MODE:
      process.env.NEXT_PUBLIC_ELEVENLABS_GUIDE_DEMO_MODE,
    NEXT_PUBLIC_ELEVENLABS_GUIDE_ENABLE_AGENT_OVERRIDES:
      process.env.NEXT_PUBLIC_ELEVENLABS_GUIDE_ENABLE_AGENT_OVERRIDES,
    NEXT_PUBLIC_ELEVENLABS_GUIDE_ENABLE_TTS_OVERRIDES:
      process.env.NEXT_PUBLIC_ELEVENLABS_GUIDE_ENABLE_TTS_OVERRIDES,
    NEXT_PUBLIC_ELEVENLABS_GUIDE_SECTION_DWELL_MS:
      process.env.NEXT_PUBLIC_ELEVENLABS_GUIDE_SECTION_DWELL_MS,
    NEXT_PUBLIC_ELEVENLABS_GUIDE_SECTION_GAP_MS:
      process.env.NEXT_PUBLIC_ELEVENLABS_GUIDE_SECTION_GAP_MS,
    NEXT_PUBLIC_ELEVENLABS_GUIDE_HIGHLIGHT_DWELL_MS:
      process.env.NEXT_PUBLIC_ELEVENLABS_GUIDE_HIGHLIGHT_DWELL_MS,
    NEXT_PUBLIC_ELEVENLABS_GUIDE_SCROLL_MS: process.env.NEXT_PUBLIC_ELEVENLABS_GUIDE_SCROLL_MS,
    NEXT_PUBLIC_ELEVENLABS_GUIDE_TTS_SPEED: process.env.NEXT_PUBLIC_ELEVENLABS_GUIDE_TTS_SPEED,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
  emptyStringAsUndefined: true,
});
