"use client";

import type { CSSProperties } from "react";

import {
  ACCENT,
  AGENT_DEFS,
  cardShell,
  CYAN,
  FONT_BLACK,
  FONT_MONO,
  FONT_SANS,
  INK,
  PAPER,
  PIPE_STEPS,
  VOLT,
} from "./defs";

const viewHeading: CSSProperties = { fontFamily: FONT_BLACK, fontSize: 24 };
const viewSub: CSSProperties = { fontSize: 13, fontWeight: 500, color: "rgba(10,10,10,0.6)", marginTop: 4 };
const kitTag: CSSProperties = {
  fontFamily: FONT_MONO,
  fontSize: 10,
  fontWeight: 700,
  letterSpacing: "0.1em",
  marginBottom: 14,
};

/* ═══════════ BRAND KIT ═══════════ */

export function BrandkitView({ brandName }: { brandName: string }) {
  return (
    <div>
      <div
        style={{
          display: "flex",
          alignItems: "baseline",
          justifyContent: "space-between",
          gap: 16,
          marginBottom: 20,
          flexWrap: "wrap",
        }}
      >
        <div>
          <div style={viewHeading}>Brand Kit</div>
          <div style={viewSub}>Generated by Brand Agent · v3 · approved by Mariana</div>
        </div>
        <button
          className="nb-press"
          style={
            {
              fontFamily: FONT_SANS,
              fontSize: 12.5,
              fontWeight: 800,
              textTransform: "uppercase",
              background: "#FFFFFF",
              border: `3px solid ${INK}`,
              padding: "9px 16px",
              cursor: "pointer",
              "--sx": "4px",
            } as CSSProperties
          }
        >
          ↻ Regenerate kit
        </button>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(330px, 1fr))", gap: 20 }}>
        <div
          style={{
            background: INK,
            color: PAPER,
            border: `3px solid ${INK}`,
            boxShadow: `5px 5px 0 ${INK}`,
            padding: 22,
            display: "flex",
            flexDirection: "column",
            gap: 18,
          }}
        >
          <div style={{ ...kitTag, marginBottom: 0, color: ACCENT }}>LOGO CONCEPT</div>
          <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
            <div
              style={{
                width: 64,
                height: 64,
                background: ACCENT,
                border: `3px solid ${PAPER}`,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                fontFamily: FONT_BLACK,
                fontSize: 30,
                color: INK,
              }}
            >
              {brandName[0]?.toUpperCase()}
            </div>
            <div style={{ fontFamily: FONT_BLACK, fontSize: 26, letterSpacing: "0.02em", textTransform: "uppercase" }}>
              {brandName}
            </div>
          </div>
          <div style={{ fontSize: 12, fontWeight: 500, color: "rgba(244,242,236,0.7)", lineHeight: 1.5 }}>
            Squared monogram — &quot;signal block&quot; motif. Reads at 16px favicon and on-device engraving.
          </div>
        </div>

        <div style={{ ...cardShell, padding: 22 }}>
          <div style={{ ...kitTag, marginBottom: 16 }}>PALETTE</div>
          <div style={{ display: "flex", gap: 0, border: `2px solid ${INK}`, height: 74 }}>
            <div style={{ flex: 1, background: INK }} />
            <div style={{ flex: 1, background: ACCENT, borderLeft: `2px solid ${INK}` }} />
            <div style={{ flex: 1, background: VOLT, borderLeft: `2px solid ${INK}` }} />
            <div style={{ flex: 1, background: CYAN, borderLeft: `2px solid ${INK}` }} />
            <div style={{ flex: 1, background: PAPER, borderLeft: `2px solid ${INK}` }} />
          </div>
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              fontFamily: FONT_MONO,
              fontSize: 9,
              marginTop: 8,
              color: "rgba(10,10,10,0.6)",
            }}
          >
            <span>CARBON</span>
            <span>ACID</span>
            <span>VOLT</span>
            <span>CYAN</span>
            <span>BONE</span>
          </div>
        </div>

        <div style={{ ...cardShell, padding: 22 }}>
          <div style={kitTag}>VOICE &amp; TONE · BILINGUAL</div>
          <div style={{ display: "flex", flexDirection: "column", gap: 10, fontSize: 12.5, fontWeight: 500 }}>
            <div style={{ display: "flex", gap: 8 }}>
              <span
                style={{
                  fontFamily: FONT_MONO,
                  fontSize: 9.5,
                  fontWeight: 700,
                  background: INK,
                  color: PAPER,
                  padding: "2px 6px",
                  flex: "none",
                }}
              >
                ES
              </span>
              Directo, seguro, un poco irreverente. Habla de foco, no de specs.
            </div>
            <div style={{ display: "flex", gap: 8 }}>
              <span
                style={{
                  fontFamily: FONT_MONO,
                  fontSize: 9.5,
                  fontWeight: 700,
                  background: INK,
                  color: PAPER,
                  padding: "2px 6px",
                  flex: "none",
                }}
              >
                EN
              </span>
              Direct, confident, lightly irreverent. Benefits over feature lists.
            </div>
            <div style={{ display: "flex", gap: 8 }}>
              <span
                style={{
                  fontFamily: FONT_MONO,
                  fontSize: 9.5,
                  fontWeight: 700,
                  border: `1.5px solid ${INK}`,
                  padding: "2px 6px",
                  flex: "none",
                }}
              >
                ✕
              </span>
              Never: corporate jargon, exclamation stacking, fake urgency.
            </div>
          </div>
        </div>

        <div style={{ ...cardShell, padding: 22 }}>
          <div style={kitTag}>BUYER PERSONA</div>
          <div style={{ fontWeight: 800, fontSize: 16, marginBottom: 8 }}>&quot;Diego, 26 — hybrid analyst, CDMX&quot;</div>
          <div style={{ fontSize: 12.5, fontWeight: 500, lineHeight: 1.55, color: "rgba(10,10,10,0.75)" }}>
            Commutes 70 min/day. Buys tech on Instagram after 2–3 touches. Cares about battery life, price-to-quality, and
            looking sharp on video calls. Deciding trigger: discount + reviews.
          </div>
        </div>

        <div style={{ ...cardShell, background: ACCENT, padding: 22 }}>
          <div style={kitTag}>VALUE PROP</div>
          <div style={{ fontFamily: FONT_BLACK, fontSize: 20, lineHeight: 1.15 }}>
            Flagship-level audio tech at a mid-range LatAm price.
          </div>
          <div style={{ display: "flex", flexWrap: "wrap", gap: 7, marginTop: 14 }}>
            {["36h battery", "Adaptive ANC", "2-yr warranty"].map((t) => (
              <span key={t} style={{ fontSize: 11.5, fontWeight: 700, border: `2px solid ${INK}`, background: PAPER, padding: "4px 9px" }}>
                {t}
              </span>
            ))}
          </div>
        </div>

        <div style={{ ...cardShell, padding: 22 }}>
          <div style={kitTag}>VISUAL STYLE</div>
          <div style={{ fontSize: 12.5, fontWeight: 500, lineHeight: 1.6, color: "rgba(10,10,10,0.75)" }}>
            Dark carbon backgrounds, acid-green accents, hard edges, product floating on grid textures. Type: condensed
            black caps for claims, mono for specs. No gradients, no lifestyle stock clichés.
          </div>
        </div>
      </div>
    </div>
  );
}

/* ═══════════ AGENTS ═══════════ */

export function AgentsView() {
  return (
    <div>
      <div style={{ marginBottom: 20 }}>
        <div style={viewHeading}>Agents</div>
        <div style={viewSub}>8 specialized collaborators. You approve; they execute.</div>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(270px, 1fr))", gap: 18 }}>
        {AGENT_DEFS.map((ag) => (
          <div key={ag.name} style={{ ...cardShell, padding: 18, display: "flex", flexDirection: "column", gap: 10 }}>
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
              <div
                style={{
                  width: 34,
                  height: 34,
                  background: ag.color,
                  border: `2px solid ${INK}`,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  fontFamily: FONT_BLACK,
                  fontSize: 13,
                }}
              >
                {ag.glyph}
              </div>
              <span
                style={{ display: "flex", alignItems: "center", gap: 6, fontFamily: FONT_MONO, fontSize: 9.5, fontWeight: 700 }}
              >
                <span
                  style={{
                    width: 7,
                    height: 7,
                    borderRadius: "50%",
                    background: ag.dot,
                    border: `1.5px solid ${INK}`,
                    animation: ag.pulse ? "pv-pulse 1.4s ease-in-out infinite" : "none",
                  }}
                />
                {ag.status}
              </span>
            </div>
            <div style={{ fontWeight: 800, fontSize: 15 }}>{ag.name}</div>
            <div style={{ fontSize: 12, fontWeight: 500, lineHeight: 1.5, color: "rgba(10,10,10,0.65)" }}>{ag.role}</div>
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                fontFamily: FONT_MONO,
                fontSize: 9.5,
                color: "rgba(10,10,10,0.55)",
                borderTop: `2px solid ${INK}`,
                paddingTop: 9,
                marginTop: 2,
              }}
            >
              <span>{ag.tool}</span>
              <span>{ag.runs} RUNS</span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

/* ═══════════ AUTOMATION ═══════════ */

export function AutomationView() {
  return (
    <div>
      <div style={{ marginBottom: 20 }}>
        <div style={viewHeading}>Automation pipeline</div>
        <div style={viewSub}>
          n8n + Supabase → Meta Ads. Fires when a campaign hits{" "}
          <span
            style={{
              fontFamily: FONT_MONO,
              fontSize: 11.5,
              background: VOLT,
              color: "#FFFFFF",
              padding: "1px 6px",
              border: `1.5px solid ${INK}`,
            }}
          >
            READY_TO_PUBLISH
          </span>
        </div>
      </div>
      <div style={{ maxWidth: 660, display: "flex", flexDirection: "column" }}>
        {PIPE_STEPS.map((ps) => (
          <div key={ps.n} style={{ display: "flex", gap: 16 }}>
            <div style={{ display: "flex", flexDirection: "column", alignItems: "center", flex: "none", width: 34 }}>
              <div
                style={{
                  width: 30,
                  height: 30,
                  border: `3px solid ${INK}`,
                  background: ps.nodeBg,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  fontFamily: FONT_MONO,
                  fontSize: 11,
                  fontWeight: 700,
                  animation: ps.pulse ? "pv-pulse 1.2s ease-in-out infinite" : "none",
                }}
              >
                {ps.n}
              </div>
              {ps.hasLine && <div style={{ width: 3, flex: 1, background: INK, minHeight: 26 }} />}
            </div>
            <div
              style={{
                background: "#FFFFFF",
                border: `3px solid ${INK}`,
                boxShadow: `4px 4px 0 ${INK}`,
                padding: "14px 18px",
                flex: 1,
                marginBottom: 16,
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                gap: 14,
              }}
            >
              <div>
                <div style={{ fontWeight: 800, fontSize: 14 }}>{ps.title}</div>
                <div style={{ fontSize: 12, fontWeight: 500, color: "rgba(10,10,10,0.6)", marginTop: 3 }}>{ps.desc}</div>
              </div>
              <span
                style={{
                  fontFamily: FONT_MONO,
                  fontSize: 9.5,
                  fontWeight: 700,
                  border: `2px solid ${INK}`,
                  padding: "3px 8px",
                  background: ps.tagBg,
                  flex: "none",
                }}
              >
                {ps.tag}
              </span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
