"use client";

import type { CSSProperties } from "react";

import type { Brand, BrandKit } from "@/lib/api";

import {
  ACCENT,
  AGENT_DEFS,
  cardShell,
  FONT_BLACK,
  FONT_MONO,
  FONT_SANS,
  INK,
  PAPER,
  PIPE_STEPS,
  VOLT,
} from "./defs";

const viewHeading: CSSProperties = { fontFamily: FONT_BLACK, fontSize: 24 };
const viewSub: CSSProperties = { fontSize: 13, fontWeight: 500, color: "rgba(10,10,10,0.6)", marginTop: 4 };
const kitTag: CSSProperties = {
  fontFamily: FONT_MONO,
  fontSize: 10,
  fontWeight: 700,
  letterSpacing: "0.1em",
  marginBottom: 14,
};

/* ═══════════ BRAND KIT ═══════════ */

export function BrandkitView({ brand, brandKit }: { brand: Brand | null; brandKit: BrandKit | null }) {
  const brandName = brand?.name ?? "Your brand";

  if (!brandKit) {
    return (
      <div>
        <div style={{ marginBottom: 20 }}>
          <div style={viewHeading}>Brand Kit</div>
          <div style={viewSub}>No brand kit generated yet — run onboarding first.</div>
        </div>
      </div>
    );
  }

  const palette = brandKit.colorPalette;
  const paletteSwatches = palette
    ? [
        { label: "PRIMARY", color: palette.primary },
        { label: "SECONDARY", color: palette.secondary },
        { label: "ACCENT", color: palette.accent },
        ...(palette.neutrals ?? []).slice(0, 2).map((color, i) => ({ label: `NEUTRAL ${i + 1}`, color })),
      ]
    : [];

  return (
    <div>
      <div
        style={{
          display: "flex",
          alignItems: "baseline",
          justifyContent: "space-between",
          gap: 16,
          marginBottom: 20,
          flexWrap: "wrap",
        }}
      >
        <div>
          <div style={viewHeading}>Brand Kit</div>
          <div style={viewSub}>Generated by Brand Agent · status: {brandKit.status}</div>
        </div>
        <button
          className="nb-press"
          style={
            {
              fontFamily: FONT_SANS,
              fontSize: 12.5,
              fontWeight: 800,
              textTransform: "uppercase",
              background: "#FFFFFF",
              border: `3px solid ${INK}`,
              padding: "9px 16px",
              cursor: "pointer",
              "--sx": "4px",
            } as CSSProperties
          }
        >
          ↻ Regenerate kit
        </button>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(330px, 1fr))", gap: 20 }}>
        <div
          style={{
            background: INK,
            color: PAPER,
            border: `3px solid ${INK}`,
            boxShadow: `5px 5px 0 ${INK}`,
            padding: 22,
            display: "flex",
            flexDirection: "column",
            gap: 18,
          }}
        >
          <div style={{ ...kitTag, marginBottom: 0, color: ACCENT }}>LOGO CONCEPT</div>
          <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
            <div
              style={{
                width: 64,
                height: 64,
                background: ACCENT,
                border: `3px solid ${PAPER}`,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                fontFamily: FONT_BLACK,
                fontSize: 30,
                color: INK,
              }}
            >
              {brandName[0]?.toUpperCase()}
            </div>
            <div style={{ fontFamily: FONT_BLACK, fontSize: 26, letterSpacing: "0.02em", textTransform: "uppercase" }}>
              {brandName}
            </div>
          </div>
          <div style={{ fontSize: 12, fontWeight: 500, color: "rgba(244,242,236,0.7)", lineHeight: 1.5 }}>
            {brandKit.logoPrompt ?? "No logo prompt available yet."}
          </div>
        </div>

        <div style={{ ...cardShell, padding: 22 }}>
          <div style={{ ...kitTag, marginBottom: 16 }}>PALETTE</div>
          {paletteSwatches.length ? (
            <>
              <div style={{ display: "flex", gap: 0, border: `2px solid ${INK}`, height: 74 }}>
                {paletteSwatches.map((s, i) => (
                  <div
                    key={s.label}
                    style={{ flex: 1, background: s.color, borderLeft: i === 0 ? "none" : `2px solid ${INK}` }}
                  />
                ))}
              </div>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  fontFamily: FONT_MONO,
                  fontSize: 9,
                  marginTop: 8,
                  color: "rgba(10,10,10,0.6)",
                }}
              >
                {paletteSwatches.map((s) => (
                  <span key={s.label}>{s.label}</span>
                ))}
              </div>
            </>
          ) : (
            <div style={{ fontSize: 12.5, color: "rgba(10,10,10,0.6)" }}>No palette generated yet.</div>
          )}
        </div>

        <div style={{ ...cardShell, padding: 22 }}>
          <div style={kitTag}>VOICE &amp; TONE · BILINGUAL</div>
          <div style={{ display: "flex", flexDirection: "column", gap: 10, fontSize: 12.5, fontWeight: 500 }}>
            <div style={{ display: "flex", gap: 8 }}>
              <span
                style={{
                  fontFamily: FONT_MONO,
                  fontSize: 9.5,
                  fontWeight: 700,
                  background: INK,
                  color: PAPER,
                  padding: "2px 6px",
                  flex: "none",
                }}
              >
                ES
              </span>
              {brandKit.toneOfVoice?.es ?? "No tone of voice generated yet."}
            </div>
            <div style={{ display: "flex", gap: 8 }}>
              <span
                style={{
                  fontFamily: FONT_MONO,
                  fontSize: 9.5,
                  fontWeight: 700,
                  background: INK,
                  color: PAPER,
                  padding: "2px 6px",
                  flex: "none",
                }}
              >
                EN
              </span>
              {brandKit.toneOfVoice?.en ?? "No tone of voice generated yet."}
            </div>
          </div>
        </div>

        <div style={{ ...cardShell, padding: 22 }}>
          <div style={kitTag}>BUYER PERSONA</div>
          <div style={{ fontWeight: 800, fontSize: 16, marginBottom: 8 }}>
            {brandKit.buyerPersona?.name ?? "No persona generated yet"}
          </div>
          <div style={{ fontSize: 12.5, fontWeight: 500, lineHeight: 1.55, color: "rgba(10,10,10,0.75)" }}>
            {[
              brandKit.buyerPersona?.occupation,
              brandKit.buyerPersona?.age && `Age ${brandKit.buyerPersona.age}`,
              ...(brandKit.buyerPersona?.goals ?? []),
              ...(brandKit.buyerPersona?.painPoints ?? []),
              brandKit.buyerPersona?.notes,
            ]
              .filter(Boolean)
              .join(". ")}
          </div>
        </div>

        <div style={{ ...cardShell, background: ACCENT, padding: 22 }}>
          <div style={kitTag}>VALUE PROP</div>
          <div style={{ fontFamily: FONT_BLACK, fontSize: 20, lineHeight: 1.15 }}>
            {brandKit.valueProposition?.es ?? "No value proposition generated yet."}
          </div>
          <div style={{ display: "flex", flexWrap: "wrap", gap: 7, marginTop: 14 }}>
            {(brandKit.keyMessages?.es ?? []).map((t) => (
              <span key={t} style={{ fontSize: 11.5, fontWeight: 700, border: `2px solid ${INK}`, background: PAPER, padding: "4px 9px" }}>
                {t}
              </span>
            ))}
          </div>
        </div>

        <div style={{ ...cardShell, padding: 22 }}>
          <div style={kitTag}>VISUAL STYLE</div>
          <div style={{ fontSize: 12.5, fontWeight: 500, lineHeight: 1.6, color: "rgba(10,10,10,0.75)" }}>
            {[brandKit.visualStyle?.mood, brandKit.visualStyle?.imageryStyle, brandKit.visualStyle?.typography]
              .filter(Boolean)
              .join(" ")  || "No visual style generated yet."}
          </div>
        </div>
      </div>
    </div>
  );
}

/* ═══════════ AGENTS ═══════════ */

export function AgentsView() {
  return (
    <div>
      <div style={{ marginBottom: 20 }}>
        <div style={viewHeading}>Agents</div>
        <div style={viewSub}>8 specialized collaborators. You approve; they execute.</div>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(270px, 1fr))", gap: 18 }}>
        {AGENT_DEFS.map((ag) => (
          <div key={ag.name} style={{ ...cardShell, padding: 18, display: "flex", flexDirection: "column", gap: 10 }}>
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
              <div
                style={{
                  width: 34,
                  height: 34,
                  background: ag.color,
                  border: `2px solid ${INK}`,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  fontFamily: FONT_BLACK,
                  fontSize: 13,
                }}
              >
                {ag.glyph}
              </div>
              <span
                style={{ display: "flex", alignItems: "center", gap: 6, fontFamily: FONT_MONO, fontSize: 9.5, fontWeight: 700 }}
              >
                <span
                  style={{
                    width: 7,
                    height: 7,
                    borderRadius: "50%",
                    background: ag.dot,
                    border: `1.5px solid ${INK}`,
                    animation: ag.pulse ? "pv-pulse 1.4s ease-in-out infinite" : "none",
                  }}
                />
                {ag.status}
              </span>
            </div>
            <div style={{ fontWeight: 800, fontSize: 15 }}>{ag.name}</div>
            <div style={{ fontSize: 12, fontWeight: 500, lineHeight: 1.5, color: "rgba(10,10,10,0.65)" }}>{ag.role}</div>
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                fontFamily: FONT_MONO,
                fontSize: 9.5,
                color: "rgba(10,10,10,0.55)",
                borderTop: `2px solid ${INK}`,
                paddingTop: 9,
                marginTop: 2,
              }}
            >
              <span>{ag.tool}</span>
              <span>{ag.runs} RUNS</span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

/* ═══════════ AUTOMATION ═══════════ */

export function AutomationView() {
  return (
    <div>
      <div style={{ marginBottom: 20 }}>
        <div style={viewHeading}>Automation pipeline</div>
        <div style={viewSub}>
          n8n + Supabase → Meta Ads. Fires when a campaign hits{" "}
          <span
            style={{
              fontFamily: FONT_MONO,
              fontSize: 11.5,
              background: VOLT,
              color: "#FFFFFF",
              padding: "1px 6px",
              border: `1.5px solid ${INK}`,
            }}
          >
            READY_TO_PUBLISH
          </span>
        </div>
      </div>
      <div style={{ maxWidth: 660, display: "flex", flexDirection: "column" }}>
        {PIPE_STEPS.map((ps) => (
          <div key={ps.n} style={{ display: "flex", gap: 16 }}>
            <div style={{ display: "flex", flexDirection: "column", alignItems: "center", flex: "none", width: 34 }}>
              <div
                style={{
                  width: 30,
                  height: 30,
                  border: `3px solid ${INK}`,
                  background: ps.nodeBg,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  fontFamily: FONT_MONO,
                  fontSize: 11,
                  fontWeight: 700,
                  animation: ps.pulse ? "pv-pulse 1.2s ease-in-out infinite" : "none",
                }}
              >
                {ps.n}
              </div>
              {ps.hasLine && <div style={{ width: 3, flex: 1, background: INK, minHeight: 26 }} />}
            </div>
            <div
              style={{
                background: "#FFFFFF",
                border: `3px solid ${INK}`,
                boxShadow: `4px 4px 0 ${INK}`,
                padding: "14px 18px",
                flex: 1,
                marginBottom: 16,
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                gap: 14,
              }}
            >
              <div>
                <div style={{ fontWeight: 800, fontSize: 14 }}>{ps.title}</div>
                <div style={{ fontSize: 12, fontWeight: 500, color: "rgba(10,10,10,0.6)", marginTop: 3 }}>{ps.desc}</div>
              </div>
              <span
                style={{
                  fontFamily: FONT_MONO,
                  fontSize: 9.5,
                  fontWeight: 700,
                  border: `2px solid ${INK}`,
                  padding: "3px 8px",
                  background: ps.tagBg,
                  flex: "none",
                }}
              >
                {ps.tag}
              </span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
